# Site settings
title: Yuvraj Singh
email: yuvrajsingh90014@gmail.com
url: https://yuvraj-singh.github.io/
description: "Software Engineer, Mathematician, Cinephile and Book Enthusiast."
meta_author: Yuvraj Singh
quote: ""When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love." - Marcus Aurelius"
about:
  header: About
  content:
      left: I work as an research engineer in the field of Machine Learning. This may not be 'it', so I am exploring things, trying to find that passion.
      right: I love to read high fantasy novels, fiction books, watch movies, lots and lots of movies and ponder Life, The Universe, and Everything.
  interests:
    header: Interests as of Late
    content:
      left:
        header: Now
        list:
          - item: Laravel
          - item: TDD
          - item: DevOps
      center:
        header: Soon
        list:
          - item: SOLID Principles
          - item: Design Patterns
          - item: Sublime Mastery
      right:
        header: Later
        list:
          - item: React
          - item: Vue
          - item: ES2015
  button:
    text: Download My Resume
    href: /resume/bill-martin-resume.pdf

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname: https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: billmartin

# If you have Google Analytics account setup, enter your tracker ID, eg. A-12312312-1
google_analytics_tracker_id: UA-126787997-1

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 101010 #80B3FF
  primary-rgb: "255,0,0" #"128,179,255"
  secondary-light: 58635a #FD6E8A
  secondary: 38433a #FD6E8A
  secondary-dark: 18231a #A2122F
  blog-text: 222
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Portfolio settings
portfolio:
  labels:
    client: Client
    project-date: Date
    application: Application
    languages: Languages
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: Manchester, NH
  copyright: Bill Martin. All Rights Reserved.
  social: My Other Whereabouts
  new-thoughts: New Thoughts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    tooltip: "Github: Code I am writing"
    url: https://github.com/yuvraj-singh
  - title: linkedin
    tooltip: "Linkedin: Places I've worked"
    url: https://www.linkedin.com/in/yuvraj-singh-621a6180/

  - title: goodreads
    tooltip: "Goodreads: Books I've been reading"
    url: https://goodreads.com/yuvraj-singh

  - title: goodreads
    tooltip: "Goodreads: Books I've been reading"
    url: https://goodreads.com/yuvraj-singh


    title: instagram
    tooltip: "Instagram: What I've been upto"
    url: https://www.instagram.com/the_yuvrajsingh/
      # - title: codeschool
      #   tooltip: "Codeschool: Skills I am learning"
      #   url: https://www.codeschool.com/users/90602
      # - title: laracasts
      #   tooltip: "Laracasts: Skills I am learning"
      #   url: https://laracasts.com/@wcmarti2
      # - title: stack-overflow
      #   tooltip: "Stack Overflow: Solutions I've been exchanging"
      #   url: http://stackoverflow.com/users/5743565/bill-martin
  # - title: rss
  #   tooltip: Subscribe to RSS feed
  #   url: /feed.xml

# Credits content
credits: '<a href="https://github.com/bill-c-martin/bill-c-martin.github.io">Fork my portfolio on github</a>'

# Build settings
permalink: pretty
